name: interconnectionchatsynpaper
version: '${version}'
main: com.foxapplication.mc.interconnectionchatsyn.paper.InterconnectionChatSynPaper
api-version: '1.20'
load: STARTUP
depend: [ interconnectionpaper ]
authors: [ KenRouKoro ]
